import { IPersonFirestore } from "../../models/person";

export const PersonsToLoad: IPersonFirestore[] = [
  { "name": "LETENRE", "surname": "Marie Jeanne", "chambreNumber": "0.001", "aileName": "Topaze", "listWeight":[] },
  { "name": "POIVRE", "surname": "Paulette", "chambreNumber": "0.001", "aileName": "Topaze", "listWeight":[] },
  { "name": "DERAUX", "surname": "Nicole", "chambreNumber": "0.002", "aileName": "Topaze", "listWeight":[] },
  { "name": "BRUNQUERS", "surname": "Simone", "chambreNumber": "0.003", "aileName": "Topaze", "listWeight":[] },
  { "name": "ROGER", "surname": "Roland", "chambreNumber": "0.004", "aileName": "Topaze", "listWeight":[] },
  { "name": "WIELEMANS", "surname": "Simone", "chambreNumber": "0.005", "aileName": "Topaze", "listWeight":[] },
  { "name": "GUELENNE", "surname": "Claudine", "chambreNumber": "0.006", "aileName": "Topaze", "listWeight":[] },
  { "name": "GAUDRONT", "surname": "Virginie", "chambreNumber": "0.007", "aileName": "Topaze", "listWeight":[] },
  { "name": "BOON", "surname": "Anne-Marie", "chambreNumber": "0.008", "aileName": "Topaze", "listWeight":[] },
  { "name": "MALCANGI", "surname": "Giuseppe", "chambreNumber": "0.009", "aileName": "Topaze", "listWeight":[] },
  { "name": "MILANTS", "surname": "Jeanne", "chambreNumber": "0.010", "aileName": "Topaze", "listWeight":[] },
  { "name": "NOTTHEGEM", "surname": "Anita", "chambreNumber": "0.011", "aileName": "Topaze", "listWeight":[] },
  { "name": "CARPENTIER", "surname": "Ghislaine", "chambreNumber": "0.012", "aileName": "Topaze", "listWeight":[] },
  { "name": "TAELMAN", "surname": "Francis", "chambreNumber": "0.013", "aileName": "Topaze", "listWeight":[] },
  { "name": "STARQUIT", "surname": "Etienne", "chambreNumber": "0.014", "aileName": "Topaze", "listWeight":[] },
  { "name": "KONINGS", "surname": "Nicole", "chambreNumber": "0.015", "aileName": "Topaze", "listWeight":[] },
  { "name": "DANIEL", "surname": "Georgette", "chambreNumber": "0.016", "aileName": "Topaze", "listWeight":[] },
  { "name": "JONARD", "surname": "Jacqueline", "chambreNumber": "0.016", "aileName": "Topaze", "listWeight":[] },

  { "name": "VANLIERDE", "surname": "Jean", "chambreNumber": "0.017", "aileName": "Améthyste", "listWeight":[] },
  { "name": "LIMAGE", "surname": "Henry", "chambreNumber": "0.017", "aileName": "Améthyste", "listWeight":[] },
  { "name": "BRICHAUX", "surname": "Mireille", "chambreNumber": "0.019", "aileName": "Améthyste", "listWeight":[] },
  { "name": "DEVERGNIES", "surname": "Léonce", "chambreNumber": "0.021", "aileName": "Améthyste", "listWeight":[] },
  { "name": "NOWACKI", "surname": "Alexis", "chambreNumber": "0.022", "aileName": "Améthyste", "listWeight":[] },
  { "name": "TREMOLADA", "surname": "Luigia", "chambreNumber": "0.024", "aileName": "Améthyste", "listWeight":[] },
  { "name": "FAYT", "surname": "Jeanne", "chambreNumber": "0.025", "aileName": "Améthyste", "listWeight":[] },
  { "name": "LARCIN", "surname": "Rita", "chambreNumber": "0.026", "aileName": "Améthyste", "listWeight":[] },
  { "name": "BRICHART", "surname": "Yolande", "chambreNumber": "0.027", "aileName": "Améthyste", "listWeight":[] },
  { "name": "FRISQUE", "surname": "Emilie", "chambreNumber": "0.028", "aileName": "Améthyste", "listWeight":[] },
  { "name": "THOMEE", "surname": "Christianne", "chambreNumber": "0.029", "aileName": "Améthyste", "listWeight":[] },
  { "name": "COLLIGNON", "surname": "Odette", "chambreNumber": "0.031", "aileName": "Améthyste", "listWeight":[] },

  { "name": "BANETON", "surname": "Raymonde", "chambreNumber": "-1.024", "aileName": "Emeraude", "listWeight":[] },
  { "name": "DERIJKE", "surname": "Odette", "chambreNumber": "-1.025", "aileName": "Emeraude", "listWeight":[] },
  { "name": "DE BRAKELEER", "surname": "Françoise", "chambreNumber": "-1.026", "aileName": "Emeraude", "listWeight":[] },
  { "name": "ROUSSEAU", "surname": "Roger", "chambreNumber": "-1.027", "aileName": "Emeraude", "listWeight":[] },
  { "name": "HAYE", "surname": "Claudine", "chambreNumber": "-1.028", "aileName": "Emeraude", "listWeight":[] },
  { "name": "MAURAGE", "surname": "Claudine", "chambreNumber": "-1.029", "aileName": "Emeraude", "listWeight":[] },
  { "name": "MOURY", "surname": "Nicole", "chambreNumber": "-1.030", "aileName": "Emeraude", "listWeight":[] },
  { "name": "SNIKERS", "surname": "Marie", "chambreNumber": "-1.031", "aileName": "Emeraude", "listWeight":[] },
  { "name": "VITARELLI", "surname": "Maria-Céleste", "chambreNumber": "-1.031", "aileName": "Emeraude", "listWeight":[] },
  { "name": "SANTUS", "surname": "Arlette", "chambreNumber": "-1.023", "aileName": "Emeraude", "listWeight":[] },
  { "name": "DEMEYERE", "surname": "Julia", "chambreNumber": "-1.022", "aileName": "Emeraude", "listWeight":[] },
  { "name": "MONTERRUBIO", "surname": "Mercedes", "chambreNumber": "-1.021", "aileName": "Emeraude", "listWeight":[] },
  { "name": "BLONDIAU", "surname": "Madeleine", "chambreNumber": "-1.020", "aileName": "Emeraude", "listWeight":[] },
  { "name": "MATTHYS", "surname": "Josianne", "chambreNumber": "-1.019", "aileName": "Emeraude", "listWeight":[] },
  { "name": "JACQUEMIN", "surname": "Christian", "chambreNumber": "-1.018", "aileName": "Emeraude", "listWeight":[] },
  { "name": "LEMPEREUR", "surname": "J-M", "chambreNumber": "-1.017", "aileName": "Emeraude", "listWeight":[] },
  { "name": "DESAEGER", "surname": "Florence", "chambreNumber": "-1.016", "aileName": "Emeraude", "listWeight":[] },
  { "name": "POIVRE", "surname": "Raymonde", "chambreNumber": "-1.016", "aileName": "Emeraude", "listWeight":[] },

  { "name": "GARIN", "surname": "Michel", "chambreNumber": "0.047", "aileName": "Azurite", "listWeight":[] },
  { "name": "BRASSEUR", "surname": "Michel", "chambreNumber": "0.047", "aileName": "Azurite", "listWeight":[] },
  { "name": "POURBAIX", "surname": "Paule", "chambreNumber": "0.048", "aileName": "Azurite", "listWeight":[] },
  { "name": "LOPEZ", "surname": "Mendez", "chambreNumber": "0.049", "aileName": "Azurite", "listWeight":[] },
  { "name": "VIAENE", "surname": "Gilbert", "chambreNumber": "0.050", "aileName": "Azurite", "listWeight":[] },
  { "name": "JOLIET", "surname": "Marie", "chambreNumber": "0.051", "aileName": "Azurite", "listWeight":[] },
  { "name": "VAN ALFAENE", "surname": "Jacqueline", "chambreNumber": "0.052", "aileName": "Azurite", "listWeight":[] },
  { "name": "DUPUIS", "surname": "Monique", "chambreNumber": "0.053", "aileName": "Azurite", "listWeight":[] },
  { "name": "MENU", "surname": "Mariette", "chambreNumber": "0.054", "aileName": "Azurite", "listWeight":[] },
  { "name": "CAPELLE", "surname": "Anne-Marie", "chambreNumber": "0.055", "aileName": "Azurite", "listWeight":[] },
  { "name": "JUSTE", "surname": "Yvette", "chambreNumber": "0.056", "aileName": "Azurite", "listWeight":[] },
  { "name": "JOURDAIN", "surname": "Julienne", "chambreNumber": "0.058", "aileName": "Azurite", "listWeight":[] },
  { "name": "SALINGROS", "surname": "Liliane", "chambreNumber": "0.059", "aileName": "Azurite", "listWeight":[] },
  { "name": "BAELEN", "surname": "Madeleine", "chambreNumber": "0.060", "aileName": "Azurite", "listWeight":[] },
  { "name": "HARDAT", "surname": "Claudine", "chambreNumber": "0.062", "aileName": "Azurite", "listWeight":[] },
  { "name": "FRANCEUS", "surname": "Willy", "chambreNumber": "0.062", "aileName": "Azurite", "listWeight":[] },

  { "name": "TASSON", "surname": "Michel", "chambreNumber": "0.032", "aileName": "Saphir", "listWeight":[] },
  { "name": "SANTUS", "surname": "Daisy", "chambreNumber": "0.033", "aileName": "Saphir", "listWeight":[] },
  { "name": "BOISDENGHIEN", "surname": "Michel", "chambreNumber": "0.034", "aileName": "Saphir", "listWeight":[] },
  { "name": "GIFFROID", "surname": "Jacques", "chambreNumber": "0.035", "aileName": "Saphir", "listWeight":[] },
  { "name": "MAURAGE", "surname": "Carmen", "chambreNumber": "0.036", "aileName": "Saphir", "listWeight":[] },
  { "name": "BRAECKMAN", "surname": "Oscar", "chambreNumber": "0.037", "aileName": "Saphir", "listWeight":[] },
  { "name": "TREZENIES", "surname": "Marie-Louise", "chambreNumber": "0.038", "aileName": "Saphir", "listWeight":[] },
  { "name": "BOURGOIS", "surname": "Philippe", "chambreNumber": "0.039", "aileName": "Saphir", "listWeight":[] },
  { "name": "VANDERMARKER", "surname": "Emilie", "chambreNumber": "0.040", "aileName": "Saphir", "listWeight":[] },
  { "name": "WAUQIER", "surname": "Alfreda", "chambreNumber": "0.041", "aileName": "Saphir", "listWeight":[] },
  { "name": "HILGERS", "surname": "Maria", "chambreNumber": "0.042", "aileName": "Saphir", "listWeight":[] },
  { "name": "LESCEUX", "surname": "Manuel", "chambreNumber": "0.043", "aileName": "Saphir", "listWeight":[] },
  { "name": "SOMERS", "surname": "Colette", "chambreNumber": "0.044", "aileName": "Saphir", "listWeight":[] },
  { "name": "JENNEPIN", "surname": "Gabrielle", "chambreNumber": "0.045", "aileName": "Saphir", "listWeight":[] },
  { "name": "SLANGEN", "surname": "Yvette", "chambreNumber": "0.046", "aileName": "Saphir", "listWeight":[] },
  { "name": "BIANCOTTO", "surname": "Jacqueline", "chambreNumber": "0.046", "aileName": "Saphir", "listWeight":[] },

  { "name": "PARADIS", "surname": "Jean Claude", "chambreNumber": "-1.001", "aileName": "Ambre", "listWeight":[] },
  { "name": "LUTHRINGER", "surname": "Bernadette", "chambreNumber": "-1.002", "aileName": "Ambre", "listWeight":[] },
  { "name": "LEDOUX", "surname": "Nadine", "chambreNumber": "-1.003", "aileName": "Ambre", "listWeight":[] },
  { "name": "GARY", "surname": "André", "chambreNumber": "-1.004", "aileName": "Ambre", "listWeight":[] },
  { "name": "SEGHERS", "surname": "Christine", "chambreNumber": "-1.005", "aileName": "Ambre", "listWeight":[] },
  { "name": "DERBAIX", "surname": "Willy", "chambreNumber": "-1.006", "aileName": "Ambre", "listWeight":[] },
  { "name": "DELHAYE", "surname": "Mariette", "chambreNumber": "-1.007", "aileName": "Ambre", "listWeight":[] },
  { "name": "PISCHETOLA", "surname": "S.", "chambreNumber": "-1.009", "aileName": "Ambre", "listWeight":[] },
  { "name": "SCHOLLAERT", "surname": "Michel", "chambreNumber": "-1.010", "aileName": "Ambre", "listWeight":[] },
  { "name": "CARLIER", "surname": "André", "chambreNumber": "-1.011", "aileName": "Ambre", "listWeight":[] },
  { "name": "SANTUS", "surname": "Guy", "chambreNumber": "-1.012", "aileName": "Ambre", "listWeight":[] },
  { "name": "INFANTINO", "surname": "Vincenzo", "chambreNumber": "-1.013", "aileName": "Ambre", "listWeight":[] },
  { "name": "PENANT", "surname": "Claudette", "chambreNumber": "-1.014", "aileName": "Ambre", "listWeight":[] },
  { "name": "COLMANT", "surname": "Philippe", "chambreNumber": "-1.015", "aileName": "Ambre", "listWeight":[] },
  { "name": "ROUSSEAUX", "surname": "André", "chambreNumber": "-1.016", "aileName": "Ambre", "listWeight":[] }
]